dataset_params:
  dataset_name: CIFAR10
  poison_type: gaussian
  poison_rate: 
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
distinguisher_params:
  mia:
    mia_type: logreg
  kld: 
    perturbation_type: gaussian
  mse: null
unlearning_methods:
  grad_ascent:
    lr: 0.001
    epochs: 10
    momentum: 0.9
    weight_decay: 5.0e-4
  scrub:
    lr: 0.001
    epochs: 10
    lr_scheduler: null
    alpha: 0.001
    beta: 0.9999
    momentum: 0.9
    weight_decay: 5.0e-4
  ssd:
    dampening_constant: 1
    selection_weighting: 100
  bad_teacher: null
  amnesiac: null
batch_size: 512
train_params:
  num_epochs: 50
  learning_rate: 1.e-2
  num_workers: 0
  pretrained: False
  use_param_norm: False
  model_type: resnet18
runs_per_forget_set: 1
